version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile    # Build based on the Dockerfile
    command: tail -f /dev/null  # Avoid container to stop
    volumes:
        - ./src:/home/docker/data/:rw  # Mount development directory

volumes:
    src: {}